/*=========================================================
                    ADVANCED SQL
=========================================================*/
-----DOANH THU TÍCH LŨY THEO THỜI GIAN-----
SELECT O.Order_Date, SUM(O.Sales) AS DAILY_REVENUE, SUM(SUM(O.SALES)) OVER(ORDER BY O.Order_Date) AS RUNNINGTOTAL
FROM dbo.Orders O
GROUP BY O.Order_Date
ORDER BY O.Order_Date


-----DOANH THU THÁNG NÀY SO VỚI THÁNG TRƯỚC-----
WITH MONTHLY_REVENUE AS(
    SELECT YEAR(O.Order_Date) AS ORDER_YEAR, MONTH(O.Order_Date) AS ORDER_MONTH, SUM(O.Sales) AS SALES
    FROM dbo.Orders O
    GROUP BY YEAR(O.Order_Date),  MONTH(O.Order_Date)
)
SELECT *, LAG(M.SALES) OVER(ORDER BY M.ORDER_YEAR, M.ORDER_MONTH)  AS  PREVIOUSMONTHREVENUE, M.SALES - LAG(M.SALES) OVER(ORDER BY M.ORDER_YEAR, M.ORDER_MONTH) AS REVENUEDIFFERENT
FROM MONTHLY_REVENUE M;


-----TOP 3 SẢN PHẨM CÓ DOANH THU CAO NHẤT THEO TỪNG DANH MỤC-----
WITH PRODUCTREVENUE AS(
    SELECT O.Category, O.Product_ID, O.Product_Name, SUM(O.Sales) AS REVENUE
    FROM dbo.Orders O
    GROUP BY O.Category, O.Product_ID, O.Product_Name
)
SELECT *
FROM(
    SELECT *, RANK() OVER(PARTITION BY P.CATEGORY ORDER BY P.REVENUE DESC) AS RANKING
    FROM PRODUCTREVENUE P) AS T
WHERE T.RANKING <=3
ORDER BY T.Category, T.RANKING;


-----XẾP HẠNG KHÁCH HÀNG THEO DOANH THU-----
WITH CUS_REVENUE AS(
    SELECT O.Customer_ID, O.Customer_Name, SUM(O.Sales) AS REVENUE
    FROM DBO.Orders O
    GROUP BY O.Customer_ID, O.Customer_Name
)
SELECT *, DENSE_RANK() OVER(ORDER BY C.REVENUE DESC) AS RANKING
FROM CUS_REVENUE C;

-----CHIA KHÁCH HÀNG THÀNH 4 NHÓM-----
WITH CUS_REVENUE AS(
    SELECT O.Customer_ID, O.Customer_Name, SUM(O.Sales) AS REVENUE
    FROM dbo.Orders O
    GROUP BY O.Customer_ID, O.Customer_Name
)
SELECT *, NTILE(4) OVER(ORDER BY C.REVENUE DESC) AS CUS_SEGMENT 
FROM CUS_REVENUE C;


-----TRUNG BÌNH DOANH THU 3 THÁNG GẦN NHẤT-----
WITH MONTHLY_REVENUE AS(
    SELECT YEAR(O.Order_Date) AS ORDER_YEAR, MONTH(O.Order_Date) AS ORDER_MONTH, SUM(O.Sales) AS REVENUE
    FROM dbo.Orders O
    GROUP BY YEAR(O.Order_Date), MONTH(O.Order_Date)
)
SELECT *, AVG(M.REVENUE) OVER(ORDER BY M.ORDER_YEAR, M.ORDER_MONTH ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MOVING_AVG_3M
FROM MONTHLY_REVENUE M;


-----SẢN PHẨM BÁN CHẠY NHẤT Ở TỪNG KHU VỰC-----
WITH PRO_REGION AS(
    SELECT O.Region, O.Product_Name, SUM(O.Sales) AS REVENUE
    FROM dbo.Orders O
    GROUP BY O.Region, O.Product_Name
)
SELECT *
FROM(
    SELECT *, ROW_NUMBER() OVER(PARTITION BY P.REGION ORDER BY P.REVENUE DESC) AS ROW_NUM
    FROM PRO_REGION P) AS T
WHERE T.ROW_NUM =1


-----DOANH THU THEO THÁNG VÀ TỈ TRỌNG ĐÓNG GÓP-----
WITH MONTHLY_REVENUE AS(
    SELECT YEAR(O.Order_Date) AS ORDER_YEAR, MONTH(O.Order_Date) AS ORDER_MONTH, SUM(O.Sales) AS REVENUE
    FROM DBO.Orders O
    GROUP BY YEAR(O.Order_Date), MONTH(O.Order_Date)
)
SELECT *, ROUND(M.REVENUE *100.0 / SUM(M.REVENUE) OVER(),2) AS REVENUE_PERCENTAGE
FROM MONTHLY_REVENUE M
ORDER BY ORDER_YEAR, ORDER_MONTH